### ISSUE TITLE
Wrong font for “min” and “s.t” in beamer class

### ISSUE THREAD

**Issue by jhelgert** [jeslago/optidef#10]
First of all I'd like to thank you for the awesome package. It's a real bless not struggling with the aligning of optimization problems by hand anymore.

Unfortunately there seems to be a problem when using optidef with the beamer class. The following MWE shows that the keywords "min" and "s.t." aren't typeset in the standard beamer font.

``` TeX
\documentclass{beamer}
\usepackage[short]{optidef}

\begin{document}
\begin{frame}[t]\frametitle{MWE}

\begin{mini*}
	{x,y}{\sum_{i=1}^{n}\sum_{j=1}^{m} a_{j}x_{ij}}{}{}
	\addConstraint{\sum_{j=1}^{m} x_{ij}}{\leq d_i,}{\forall i=1,\ldots,n}
	\addConstraint{x_{ij}}{\in \{0,1\}}{}
\end{mini*}

VS

\[
	\min_{x,y}
\]
\end{frame}
\end{document}

```

[mwe.pdf](https://github.com/jeslago/optidef/files/1629466/mwe.pdf)

**Comment by jeslago** [comment]
The reason for that is because the optidef package uses the math-roman (\mathrm) as default for the mathematical definitions.

By default, the beamer class might be using the san-serif font, and that is why you see a discrepancy. To get the optidef definitions to display the equations in the san serif font, there are three options:

1. In the long term, I should be adding the possibility within the package. But for now, I do not have time to implement it.

2. As a quick hack, if you do not use the \mathrm command in your presentation, you can simply add \renewcommand{\mathrm}{\mathsf} after importing optidef.

3. If you want to keep the comand \mathrm as it is, you can download the optidef.sty file and simply replace every occurrence of \mathrm by \mathsf.
