### ISSUE TITLE
customized tag required

### ISSUE THREAD

**Issue by AdrianMyth233** [jeslago/optidef#31]
Dear developer, thanks for your contribution! But now I have to type an optimization problem with a customized tag behind it, like (LP)/(NLP)/... etc, hope you can give me the introduction.

**Comment by jeslago** [comment]
Can you provide an example? Where do you need that label to be?

**Comment by jeslago** [comment]
I close the issue do inactivity

**Comment by tianyizheng02** [comment]
Hi @jeslago, I have the same question/feature request, so I'd appreciate it if you could reopen this issue.

I'm typesetting some LP problems with the `mini` environment, and I want to have custom tags for the problems instead of automatic numbering. For example, if I want to typeset a LP problem and its dual, I want to tag the original problem as (P) and its dual as (D) for clearer reference, instead of (1) and (2).

I think @mythmyp's use case is similar. I suspect they want to compare/contrast a linear programming problem with a nonlinear programming problem, and want to tag the LP problem with (LP) and the NLP problem with (NLP).

For both of our use cases, we just want to customize the text in the tag, not its location. I couldn't find how to customize the tag text in the `optidef` package documentation.
