### ISSUE TITLE
mini! clashes with journal class / option [proc]edpsmath

### ISSUE THREAD

**Issue by fmesserer** [jeslago/optidef#34]
Hi,
I am currently writing a paper using the class edpsmath with options edpsproc, as can be downloaded here: https://www.esaim-proc.org/author-information/latex2e-macro-package

This is somehow clashing with the mini! environment (mini and mini* work fine)

The error message is: 
> ! LaTeX Error: \begin{mini!} on input line 7 ended by \end{mini!}.

It still produces a pdf though and typesets the optimization problem as intended.
Version of optidef is 3.1

MWE:
```
\documentclass[proc]{edpsmath}
\usepackage{optidef}
\begin{document}
\begin{mini!}
	{}{f(x)}
	{}{}
	\addConstraint{g(x)}{= 0}
\end{mini!}
\end{document}
```

Do you have any idea of a quick fix? Thanks!

**Comment by jeslago** [comment]
Hi,

I see the problem, but it is a bit hard to understand. There is some clash  with the package babel and the language frenchb. I am not sure how to solve it because I do not fully understand it.

As a workaround, if you don't need the French support, you can comment the lines 486--510 in edpsmath.cls and remove frenchb from the list of options that you passed to babel.

**Comment by fmesserer** [comment]
oh wow, that seems involved

thanks!
