### ISSUE TITLE
Optimization variables in \scriptstyle

### ISSUE THREAD

**Issue by avsaase** [jeslago/optidef#36]
Thanks for this package. It really helps to nicely typeset optimization problems. However, I think the variables over which the objective function is optimized should by default be typeset with `\scriptstyle` instead of normal size, just as with the standard `\max_{}`, `\min_{}`, etc. functions.

**Comment by jeslago** [comment]
Thanks for the remark. I think it is a matter of style preference. Personally, I dislike the output of `\scriptstyle` because the variables look too tiny, so by default the package the package doesn't use `\scriptstyle`. However, you can easily add it yourself by including it in the variables input of the environment:

```
\documentclass{article}

\usepackage[nocomma]{optidef}

\begin{document}

\begin{mini!}[2]
{\scriptstyle x,y}{f(x,y)}{}{}
	\addConstraint{g(x,y)}{=0}{}
\end{mini!}

\end{document}
```
