### ISSUE TITLE
[Feature Request] Customize alignments for objective and constraints

### ISSUE THREAD

**Issue by snowztail** [jeslago/optidef#43]
It would be very much appreciated if the developers can add an option to align the (potentially long) objective and constraints at a specific position. For example,

![Screenshot_20210909_090348](https://user-images.githubusercontent.com/30973137/132647578-1029174b-f796-4764-8ed7-7f79e7bb330a.png)

looks better to me. Using `\breakObjective` only aligns the multirow objective to the left and may looks a little bit messy when the equal sign is involved:

![Screenshot_20210909_084108](https://user-images.githubusercontent.com/30973137/132643987-a59e600c-ee42-48a7-a50d-ce74fbc5b8b6.png)

Thanks for your attention.

_Environment: optidef 2019/04/23 - version=3.1_

**Comment by jeslago** [comment]
This is complex (I think even impossible) because the objective does not contain alignment points. This is done to decouple the format of the objective w.r.t. constraints. If we were to introduce alignment points in the objective, they will mess with the contraint alignments.

A hack is to use `\quad` or other spacing to add space in the second line of the objective.
