### ISSUE TITLE
Problem with bmatrix environment in the right hand side of a constraint

### ISSUE THREAD

**Issue by mkatliar** [jeslago/optidef#9]
Minimal failing example:
```latex
\begin{mini*}
	{x,y}{f(x,y)}
	{}{}
	\addConstraint{0}{\leq \begin{bmatrix} x \\ y \end{bmatrix}}
\end{mini*}
```
works if changed to
```latex
\begin{mini*}
	{x,y}{f(x,y)}
	{}{}
	\addConstraint{0\leq \begin{bmatrix} x \\ y \end{bmatrix}}{}
\end{mini*}
```

**Comment by jeslago** [comment]
Hi,

first of all, sorry for the time it took to reply. Second, thanks a lot for the feedback, it was very helpful to spot a bug.

So the problem was with a latex fragile command within the library that did not accept \begin{matrix}. I think I have fixed it.

Can you check if the github version works for you now?

**Comment by mkatliar** [comment]
It works now, thank you for fixing it!
